### ISSUE TITLE
What happens when I run the sync version of efn from ipython

### ISSUE THREAD

**Issue by bhaugen** [Punto0/faircoin_nrp#15]
Works ok, but after each of the sets of logging notifications I need to hit enter to get ipython to respond again. I wonder if that is what hangs django?

```
In [20]: rec_tx_out = efn.make_transaction_from_address(address_origin, address_end, 1.0)
using 1 inputs
change 99000
adding signature for ff0488b21e0000000000000000005139a8f83ca595c338303374bb07fbc341f92e7e1c83966b3570089375a4e1f90384db0f3cf226cba428f68928ac2da1ce3189c6e722be8717834da8fe85fd746600000100
is_complete True

[profiler] save_transactions 0.0116
[WalletSynchronizer] receiving history fbuVYDupmaBm7hSSmh4So8tYUABxfQadf5 2
[WalletSynchronizer] receiving history fPhpxGqcnWPkj9GFZrqmmmG1JEfikWe1r4 8
[WalletSynchronizer] received tx: 485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c 462
[profiler] save_transactions 0.0081


In [21]: rec_tx_out
Out[21]: u'485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c'

In [22]: efn.get[WalletSynchronizer] receiving history fbuVYDupmaBm7hSSmh4So8tYUABxfQadf5 2
removing tx from history 485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c
[SPV] requesting merkle 485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c
[WalletSynchronizer] receiving history fPhpxGqcnWPkj9GFZrqmmmG1JEfikWe1r4 8
removing tx from history 485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c
[SPV] verified 485a93f0356b4ac79e6ec6f501a1ee433efdf1ac39e369269e629b66b8ed670c
[profiler] save_transactions 0.0084


In [23]: tx_hash = rec_tx_out

In [24]: efn.get_confirmations(tx_hash)
Out[24]: (2, 1462271710)
```

**Comment by XaviP** [comment]
It seems that _electrum-fair_ uses _threading module_ as a _thread object_:
https://docs.python.org/2/library/threading.html#thread-objects
Searching in internet it can be found a lot of issues with django and threading module. Some simply discourage the use of threading in a request/response system like django (not a good practice to wait for a response of a thread in a web response), but some others have really problems like the one you have described.
So, if we don't find an easy solution for this, maybe we can reorient it to make an asynchronous call, and try to run a cron checker for the confirmations of the new transactions.

**Comment by bhaugen** [comment]
In the transaction states, between new, pending, broadcast and confirmed:
* does 1 confirmation mean broadcast: that is, the network now has the transaction, and no confirmations mean it has not been accepted by the network yet?
* or what does signal that the transaction exists on the network and django can just check back later to see if it is confirmed?

This question is about what does the cron checker (or whatever) need to do to make sure the transaction exists? Because I think I had one transaction that I sent async disappear. Not sure about all the symptoms. If we decide to go with async transactions, I'll do a lot more testing with that method.

**Comment by bhaugen** [comment]
Here's the wallet code for both sync and async:
```
    def sendtx(self, tx):
        # synchronous
        h = self.send_tx(tx)
        self.tx_event.wait()
        return self.receive_tx(h, tx)

    def send_tx(self, tx):
        # asynchronous
        self.tx_event.clear()
        self.network.send([('blockchain.transaction.broadcast', [str(tx)])], self.on_broadcast)
        return tx.hash()

    def on_broadcast(self, r):
        self.tx_result = r.get('result')
        self.tx_event.set()

    def receive_tx(self, tx_hash, tx):
        out = self.tx_result
        if out != tx_hash:
            return False, "error: " + out
        run_hook('receive_tx', tx, self)
        return True, out
```
sendtx, the sync method, calls the async method and then event.wait(), and then calls receive_tx() which checks for tx_result.

Not sure what run_hook does...?

**Comment by XaviP** [comment]
> does 1 confirmation mean broadcast: that is, the network now has the transaction, and no confirmations mean it has not been accepted by the network yet?

I think that one confirmation means that the electrum-server has sent the transaction to its faircoind (who lives in the same machine). So, at least, the transaction has been confirmed by the faircoind in electrum-server. I think it can be tagged as BROADCASTED yet.

> Not sure what run_hook does...?

I don't know either.
Line 39: from plugins import run_hook
https://pypi.python.org/pypi/Plugins/0.5a1dev

**Comment by bhaugen** [comment]
@XaviP  thanks for the response. 
> I think it can be tagged as BROADCASTED yet.

Was that a typo? Did you mean you don't  think it has been broadcasted? Or that it has? I ask because I understood your previous statements to mean that it has not been accepted by the network after one confirmation.

**Comment by XaviP** [comment]
No typo, the transaction can be considered broadcasted, as it has arrived to, at least, one node of the network.

**Comment by bhaugen** [comment]
Great! Thanks.

**Comment by bhaugen** [comment]
ipython log from my next test, below:

```
### this test will use the async version of efn.make_transaction_from_address
### I expect to receive a transaction
### then: out = wallet.receive_tx(self, tx_hash, tx)
### which might tell me if the tx was broadcast
### or: efn.get_confirmations(tx)

address_origin = balances[1]
efn.get_address_balance(address_origin)
#[Out]# (1199000, 0, 0)
bal = efn.get_address_balance(address_origin)
bal = bal / 1.e6
bal = bal[0] / 1.e6
bal
#[Out]# 1.199
address_end = bob.address
efn.get_address_balance(bob_address)
#[Out]# (14948000, 0, 0)
wallet
#[Out]# <electrum_fair.wallet.NewWallet object at 0x33e4510>
address_origin
#[Out]# 'fXnkpnUMCmc5YtfWNThyWyzzuKL1JFmoj6'
address_end
#[Out]# u''
address_end = bob_address
address_end
#[Out]# u'fPhpxGqcnWPkj9GFZrqmmmG1JEfikWe1r4'
amount = 1.0
tx = efn.make_transaction_from_address(address_origin, address_end, amount)
tx
#[Out]# <electrum_fair.transaction.Transaction instance at 0x3570e18>
tx_hash = tx.hash()
tx_hash
#[Out]# 'cee330efbbadcd69f3416cd6cb0160f5e9871580ec1857ca736a4cb47ce469c8'
out = wallet.receive_tx(tx_hash, tx)
out
#[Out]# (True, u'cee330efbbadcd69f3416cd6cb0160f5e9871580ec1857ca736a4cb47ce469c8')

### that - wallet.receive_tx(tx_hash, tx) - is the end of the synchronous tx method
### wallet.sendtx()

efn.get_confirmations(tx_hash)
#[Out]# (0, None)
efn.get_confirmations(tx_hash)
#[Out]# (0, None)
efn.get_confirmations(tx)
#[Out]# (0, None)
efn.get_confirmations(tx)
#[Out]# (0, None)
efn.get_confirmations(tx)
#[Out]# (0, None)
efn.get_confirmations(tx)
#[Out]# (0, None)
bal = efn.get_address_balance(address_origin)
bal
#[Out]# (1199000, -1000000, 0)
efn.get_address_balance(bob_address)
#[Out]# (14948000, 999000, 0)
efn.get_confirmations(tx)
#[Out]# (0, None)
efn.get_confirmations(tx_hash)
#[Out]# (0, None)
# get the balance for a determined address
# Returns a tupla with 3 values: Confirmed, Unmature, Unconfirmed
# from the wallet doc:
# return the balance of a bitcoin address: confirmed and matured, unconfirmed, unmatured
efn.get_confirmations(tx_hash)
#[Out]# (0, None)
efn.get_confirmations(tx_hash)
#[Out]# (0, None)

### this was maybe 10 minutes after sending the tx
### we talk a walk for 45 minutes
### this (below) is after we returned from our walk
### so tx confirmation took somewhere between 10 and 45 mins.

efn.get_confirmations(tx_hash)
#[Out]# (8, 1462284912)
```

**Comment by XaviP** [comment]
Good, so receive_tx() seems faster than get one confirmation, maybe it's better for control if the transaction has been broadcasted :-)

**Comment by bhaugen** [comment]
Can I assume if receive_tx() returns True that the tx has been broadcasted?

**Comment by XaviP** [comment]
I think so, it's the way the sync function returns the response from the server (tx_hash). So, I think you're doing the same as sync function but without using threading. I don't know how much time needs the server to answer, I'm going to make some test too.

**Comment by bhaugen** [comment]
> I'm going to make some test too.

Me too. And I'll get some exact timings. Seemed pretty fast, and did not hang.

**Comment by bhaugen** [comment]
Another test:
elapsed time until receive_tx() returns True: 0.00030994415283203125 secs
elapsed time until first confirmation: 35.25059509277344 secs (lots better than the last test)

**Comment by bhaugen** [comment]
Afterword: I tried 
tx.get_fee()
which failed because it called self.input_value()
```
    def get_fee(self):
        return self.input_value() - self.output_value()
    def input_value(self):
        return sum(x['value'] for x in self.inputs)
```
which failed because the transaction inputs had no keyword 'value':
```
In [82]: tx.inputs
Out[82]: 
[{'address': 'fLqgo4HKzWeNFdnF9ZFuEkUYn3eaui3fnP',
  'is_coinbase': False,
  'num_sig': 1,
  'prevout_hash': '9b7769319b10259331f8059953296082e2dfde928967c43fb7bebdc3cc501c1a',
  'prevout_n': 0,
  'pubkeys': ['02198c0b6f013ab4905ccda6e860a9c257fb8320adde749e7395294f09c2186b15'],
  'scriptSig': '493046022100a1a190732ad98074b21388a016befd60cdebb5970043de1ac4107eb9d49aebcd022100ae18ff1d6d829fbb4cd270e9d5b0693bd31d5ecf7c31e20b6936480bb9f4e259012102198c0b6f013ab4905ccda6e860a9c257fb8320adde749e7395294f09c2186b15',
  'sequence': 4294967295,
  'signatures': ['3046022100a1a190732ad98074b21388a016befd60cdebb5970043de1ac4107eb9d49aebcd022100ae18ff1d6d829fbb4cd270e9d5b0693bd31d5ecf7c31e20b6936480bb9f4e259'],
  'x_pubkeys': ['02198c0b6f013ab4905ccda6e860a9c257fb8320adde749e7395294f09c2186b15']}]
```
Does this indicate something wrong with my transaction or a bug in tx.input_value()?

**Comment by XaviP** [comment]
> elapsed time until receive_tx() returns True: 0.00030994415283203125 secs

Yes, it's very fast for me too. However, maybe we can send the transaction asynchronously, make the respose http to the user, and from the client make an ajax call to get recieve_tx() or get_confirmations() info. Do you think it worth it?

> Does this indicate something wrong with my transaction or a bug in tx.input_value()?

In all my transactions there's no input value, not in "internal" nor in "externals" ones. So, it's not a problem with your transaction. I don't think it's a bug of tx.input_value(), maybe we are calling the function in a not correct way.

**Comment by bhaugen** [comment]
> maybe we can send the transaction asynchronously, make the respose http to the user, and from the client make an ajax call to get recieve_tx() or get_confirmations() info. Do you think it worth it?

I am mirroring the faircoin tx in an OCP economic event which keeps track of its state. Every time the economic event is observed, for whatever reason, I plan to check its state. 
* if it is not yet broadcast, I will call receive_tx() and set the state to "broadcast" if True.
* if it is not yet confirmed, I will call get_confirmations() and set the state to "confirmed" if >= 6.

Make sense?

**Comment by XaviP** [comment]
Oh, good. The only problem could be if, for any reason, the transaction has not been broadcasted. Using the async function we don't know if there's an error when sent. The transaction will remain in NEW state forever.

**Comment by bhaugen** [comment]
Change of plans: can't call receive_tx() later if I don't have a handle on the real tx. All I save is the tx_hash, and I don't know how to get the real tx given the tx_hash. So I am calling receive_tx immediately. Might put it in a short loop to simulate wait. And after that, just calling get_confirmations().

Also, efn.make_transaction_from_address() handles a bunch of errors, and the immediate receive_tx() will also signal problems. 

When I think I have all this stuff working, I will document it and point to the pieces of code involved and maybe you guys can give me some code review?

**Comment by bhaugen** [comment]
I finally got FC transactions working from django (I think).
Getting a response from receive_tx() took longer than in ipython. I didn't time it, but put it in a loop, and never got a response. Worked fine later when I checked it from the event history. Still needs some refinements...

**Comment by bhaugen** [comment]
I was doing well, got a few successful transactions, and then I got another one that went into limbo.

Never got any confirmations (so far, this 30 minutes later). Not found by the chain. Don't know yet how to detect this. receive_tx() does not give good error messages. If wallet.tx_result does not exist, it just crashes. And it takes an unknown length of time for wallet.tx_result to appear.

I'll figure something out, but if you know a better method of figuring out if a transaction was accepted by the wallet, I'd be interested. This is my current blocker.

```
    def receive_tx(self, tx_hash, tx):
        out = self.tx_result
        if out != tx_hash:
            return False, "error: " + out
        run_hook('receive_tx', tx, self)
        return True, out
```

**Comment by bhaugen** [comment]
Not blocked anymore, using cronjob to broadcast tx.
