### ISSUE TITLE
How to determine if a FairCoin transaction has been accepted by the network using the asynchronous send_tx() method

### ISSUE THREAD

**Issue by bhaugen** [Punto0/faircoin_nrp#16]
This is my current blocker. Django hangs if I use wallet.sendtx(), the synchronous method. And I do not yet know how to determine reliably if a transaction has been acccepted by the network using the asynchronous method.

I am leaving this issue here for now, because a lot of transactions succeed, and the code to detect acceptance is localized. I have one place to send faircoins now, from an individual agent's address to any other faircoin address. I also need to set up ways to accept faircoins coming in for distribution to workers, and then to distribute them to the workers. So I will start working on those use cases, and come back and resolve this issue later. It will be the same code to resolve the issue for distributing faircoins to coop workers. I'll document the situation better later, or on request.

**Comment by bhaugen** [comment]
Here is the electrum_fair_nrp method that I changed from synchronous to async. I commented out the original lines of code that I changed so you can see the original next to the changes.
```
# make a transfer from an adress of the wallet 
def make_transaction_from_address(address_origin, address_end, amount):
    if not is_mine(address_origin): 
        logging.error("The address %s does not belong to this wallet" %address_origin)
        return False
    if not is_valid(address_end):
        logging.error("The address %s is not a valid faircoin address" %address_end)
        return False

    inputs = [address_origin]
    coins = wallet.get_spendable_coins(domain = inputs)
    #print coins
    amount_total = ( 1.e6 * float(amount) ) - float(network_fee)
    amount_total = int(amount_total)

    if amount_total > 0:
        output = [('address', address_end, int(amount_total))] 
    else:
        logging.error("Amount negative: %s" %(amount_total) )
        return False
    try:
        tx = wallet.make_unsigned_transaction(coins, output, change_addr=address_origin)
    except NotEnoughFunds:
	        logging.error("Not enough funds confirmed to make the transaction. %s %s %s" %wallet.get_addr_balance(address_origin))
                return False
    wallet.sign_transaction(tx, password)
    #rec_tx_state, rec_tx_out = wallet.sendtx(tx)
    rec_tx_out = wallet.send_tx(tx)
    #if rec_tx_state:
    if rec_tx_out:
         logging.info("SUCCESS. The transaction has been broadcasted.")
         #return rec_tx_out
         return tx
    else:
         logging.error("Sending %s fairs to the address %s" %(amount_total, address_end ) )
         return False
```

I'm calling it from this method. efn is electrum_fair_nrp. I tagged the place where I want to learn how to detect broadcast success or failure. Sometimes a valid tx succeeds, sometimes it fails, and I don't know how to tell the difference except by waiting so long that the browser will timeout.
```
def send_faircoins(address_origin, address_end, amount):
    #import pdb; pdb.set_trace()
    init_electrum_fair()
    wallet = efn.wallet
    tx = efn.make_transaction_from_address(address_origin, address_end, amount)
    tx_hash = tx.hash()
    print "tx_hash in send_faircoins:", tx_hash
    # this is my feeble attempt to determine
    # if the transaction has been broadcasted.
    # It does not work, doesn't wait long enough.
    # And cannot actually tell if the tx has failed
    # to be accepted by the network.
    ##### That's what I want to learn how to do.
    broadcasted = False
    for i in range(0, 32):
        try:
            wallet.tx_result
            print "wallet.tx_result"
        except AttributeError:
            continue
        if broadcasted:
            print "broadcast break"
            break
        broadcasted, out = wallet.receive_tx(tx_hash, tx)
    return tx, broadcasted
```

Here are the wallet methods that are being called, including the synchronous method so you can see how it worked.
```
    def sendtx(self, tx):
        # synchronous
        h = self.send_tx(tx)
        self.tx_event.wait()
        return self.receive_tx(h, tx)

    def send_tx(self, tx):
        # asynchronous
        self.tx_event.clear()
        self.network.send([('blockchain.transaction.broadcast', [str(tx)])], self.on_broadcast)
        return tx.hash()

    def on_broadcast(self, r):
        self.tx_result = r.get('result')
        self.tx_event.set()

    def receive_tx(self, tx_hash, tx):
        out = self.tx_result
        if out != tx_hash:
            return False, "error: " + out
        run_hook('receive_tx', tx, self)
        return True, out
```

**Comment by XaviP** [comment]
Hi Bob,
I've been reading the _network_ module and it seems that uses a kind of stack of messages to send to the server. So, in somehow it's not really asynchronous, and maybe your checking is in queue waiting for I don't know what. Some notes about possible solutions:
- Find the way to active the sending of the messages stack.
- Make an ajax checking from client browser (I have some hope about when the page is served, the messages stack would be cleared) Here's a jquery example:
```
jQuery(document).ready(function($){

  tx = jQuery("#transaction-id").text() //get transaction from a html element.

  jQuery.ajax({
    type: 'GET',
    url: "http://url.ocp.com/check_transaction?tx=" + tx,
    async: true,
    contentType: "application/json",
    dataType: 'jsonp',
    success: function(data) {
      jQuery("#status-transaction").html('Broadcasted!');
    }
  });

});
```
(The url `http://url.ocp.com/check_transaction?tx=tx` has to be setup in url.py and integrate the checking function in it, returning a json with transaction state.)
- Make the checking through a shell command (using [subprocess module](https://docs.python.org/2/library/subprocess.html))
- Return to the idea of faircoin_nrp as a daemon.

Hope it helps.

**Comment by bhaugen** [comment]
@XaviP thanks a lot! I'm working on the code to distribute faircoins to coop workers now, but then will return to this issue and work through your suggestions. I think there will be a way to make this work without going back to efn as a daemon; we already got the electrum-fair daemon running.

Will start by following the network message stack clue, and move on from there.

**Comment by bhaugen** [comment]
Ok, I am done roughing out all the other faircoin functions except how the income arrives at OCP to be distributed. Once it arrives, OCP can distribute it.

This issue is the biggest remaining problem, and what I will focus on next.

**Comment by bhaugen** [comment]
Here's what I think I know so far:
https://docs.python.org/2/library/threading.html
> In CPython, due to the Global Interpreter Lock, only one thread can execute Python code at once
> threading.Event()
A factory function that returns a new event object. An event manages a flag that can be set to true with the set() method and reset to false with the clear() method. The wait() method blocks until the flag is true.

In other words, when sendtx does ```self.tx_event.wait() ```, django, operating on the same interpreter, hangs until on_broadcast() is called to reset the event flag to True.

I put a pdb halt in on_broadcast() last night. As of this morning, it still has not been called. So sendtx will not work with django. And send_tx cannot be relied upon to broadcast transactions.

I have a list of 9 test transactions. 5 have been confirmed, 4 have not been broadcasted. And as far as I can tell, never will be. @XaviP @Punto0 does this match your experience?

Gotta follow the thread farther to find out what is happening with the broadcast...

**Comment by XaviP** [comment]
> So sendtx will not work with django.

:-( 
And as I see, send_tx() depends on threading too: [send_tx](https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/lib/wallet.py#L971), [tx_event](https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/lib/wallet.py#L183), [import threading](https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/lib/wallet.py#L23).

Maybe tx_event() is not calling tx_event.wait(), but uses [network.send()](https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/lib/network_proxy.py#L122) which is calling [lock() ](https://github.com/FairCoinTeam/electrum-fair/blob/2.3.3/lib/network_proxy.py#L42), a method of threading, and it works with a queue of unanswered requests. So, it's not really asynchronous.

I don't see an easy solution. Even with ajax calls, it could be collapsed too.
I keep on searching.

**Comment by bhaugen** [comment]
The ajax call will not help. I call get_confirmations every time I display the transactions on a page. Some transactions never get any confirmations, and also are not found if I try to look them up on the chain. (This is sometimes after several days.) I conclude that they never got broadcast at all.

**Comment by XaviP** [comment]
Other solutions:
- call to the server directly with [stratum protocol](http://docs.electrum.org/en/latest/protocol.html) ( [here an example](http://bitcoin.stackexchange.com/questions/36988/how-can-i-run-an-electrum-console-command-from-outside-electrum-in-linux#37000) with python 3 )
- call to electrum-fair with [subprocess module](https://docs.python.org/2/library/subprocess.html), as a console command.
- run faircoin_nrp as a daemon (@Punto0 said that fairmarket is running this way)

**Comment by bhaugen** [comment]
Does fairmarket have the same experience with transactions that never get broadcasted?

**Comment by bhaugen** [comment]
That's the part that is most confusing me now: the failure rate on faircoin transactions. Almost half of those I send fail to get broadcasted.

Other than that, the aync method works fine, and that is also what the sync method uses, except for the thread event.wait(). But maybe that is the critical thing, and is not compatible with django running on the same thread. If so, trying to do this async without using a different process will not work.

**Comment by Punto0** [comment]
No, in FairMarket if the result is success the transaction is broadcasted, never noticed about that.

**Comment by XaviP** [comment]
So, @bhaugen do you want us to change electrum_fair_nrp for working as a daemon? The idea is that you won't have to change anything that has been developed yet.

**Comment by bhaugen** [comment]
Not yet. Let me do a few more tests. Today is a travel day for us, so I won't get them done until tomorrow.

**Comment by bhaugen** [comment]
Did one test, using the original sync version electrum_fair_nrp using sendtx, invoking from ipython. 
Works well, tx gets broadcasted very quickly, ipython does not hang.

So one question is to see if I can figure out why Django hangs and ipython does not.

But probably a more productive question is what will I need to do from Django if electrum_fair_nrp is running as a daemon? Because it is looking more like that will be what to do. Don't do it yet, I'm still thinking.

**Comment by bhaugen** [comment]
Followup questions about electrum_fair_nrp as daemon:
* How do you do it in fairmarket? You probably told me, but I don't remember. And if I could look at the code, that would be even better.
* Would it make sense only to make make_transaction_from_address into a daemon? Everything else I have tried works fine from Django. It's just the sendtx that hangs.
* I'm studying [bitcoins in a Django application](https://opensourcehacker.com/2013/10/16/accepting-and-spending-bitcoins-in-a-django-application/) and may have more questions about that later. From an initial scan (don't have much time now, on the road soon), it looks like they are using a cron job to check transactions.

**Comment by bhaugen** [comment]
More about efn as daemon:
> Would it make sense only to make make_transaction_from_address into a daemon? Everything else I have tried works fine from Django. It's just the sendtx that hangs.

I'm not at all sure I am thinking about this correctly, because I have no experience using threads or daemons from Django or even Python, but that seems like a possible solution. In fact, I am not even sure it requires making efn into a daemon.

The simplest way I can think of to deal with it is to put the new transactions in the database as an EconomicEvent (which I am already doing), and then have a cron job that runs every minute or so to call efn.make_transaction_from_address() for each new tx, and when the tx_hash returns, add it to the EconomicEvent record in the database and change the tx_state to "broadcast". 

Would that require a daemon?

Also, I think I would need to do some locking around the send because if many transactions are being sent, the cron job could be busy. We use django-notifications to send emails, which does something like that. Here's their [lockfile technique](https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/lockfile.py), and here's [their code that calls it](https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/engine.py#L21).

Does that all make sense? If not, please let me know.

**Comment by bhaugen** [comment]
I got a django management command that just calls efn.make_transaction_from_address for new transactions and could be run from a cron job. It is fast, and does not hang. I don't think it requires any changes to electrum_fair_nrp.

**Comment by bhaugen** [comment]
I think I got all this stuff working now. See https://github.com/FreedomCoop/valuenetwork/issues/10 and https://github.com/FreedomCoop/valuenetwork/issues/11
